AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Custom Runtime

Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Custom Runtime 
      Runtime: Provided
      CodeUri: .
      Handler: custom
      MemorySize: 512
      Timeout: 10
      Policies: 
        - AWSLambdaRole
